apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: {{ include "csi-driver-node.provisioner" . }}
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
