{{- if eq .Values.gardener.seed.provider "openstack" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gardener-cloud.fast
  labels:
{{ include "labels" . | indent 4 }}
provisioner: kubernetes.io/cinder
allowVolumeExpansion: true
{{- end }}
