cloudProviderConfig: |
  <cloud-provider-config>

images:
  csi-driver-cinder: image-repository:image-tag
  csi-node-driver-registrar: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag

socketPath: /csi/csi.sock

resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 80Mi
